name = "anthares-control"
main = "src/index.js"
compatibility_date = "2026-10-04"
workers_dev = true

[[kv_namespaces]]
binding = "ANTHARES_STATE"
id = "d5ca2033673040babc9fd701cc0c8738"

[[durable_objects.bindings]]
name = "ANTHARES_QUEUE"
class_name = "AntharesQueue"

[[migrations]]
tag = "v1-queue-sqlite"
new_sqlite_classes = ["AntharesQueue"]

[triggers]
crons = ["*/5 * * * *"]

