package us.anthares.agent;
import android.accessibilityservice.AccessibilityService; import android.view.accessibility.AccessibilityEvent; import android.view.accessibility.AccessibilityNodeInfo; import java.util.*;
public class AntharesAccessibilityService extends AccessibilityService {
 private static final String KWAI="com.kwai.video"; private KwaiState state=KwaiState.BOOT;
 @Override public void onAccessibilityEvent(AccessibilityEvent e){ if(e==null||e.getPackageName()==null||!KWAI.contentEquals(e.getPackageName()))return; AccessibilityNodeInfo root=getRootInActiveWindow(); if(root==null)return; KwaiState next=detect(root); if(next!=state){state=next;log("STATE",state.name());}}
 @Override public void onInterrupt(){log("SERVICE","INTERRUPTED");}
 private KwaiState detect(AccessibilityNodeInfo root){String s=snapshot(root).toLowerCase(Locale.ROOT);if(hasAny(s,"resource downloading","downloading resources"))return KwaiState.RESOURCE_LOADING;if(hasAny(s,"password","senha","verification code","código de verificação","log in","login","entrar"))return KwaiState.LOGIN_REQUIRED;if(hasAny(s,"edit profile","editar perfil")&&hasAny(s,"followers","seguidores"))return KwaiState.AUTHENTICATED;if(findById(root,"ll_profile")!=null)return KwaiState.MAIN;return KwaiState.UNKNOWN_UI;}
 public boolean clickSemantic(String... needles){AccessibilityNodeInfo root=getRootInActiveWindow();if(root==null)return false;ArrayDeque<AccessibilityNodeInfo>q=new ArrayDeque<>();q.add(root);while(!q.isEmpty()){AccessibilityNodeInfo n=q.remove();String t=nodeText(n).toLowerCase(Locale.ROOT);for(String x:needles)if(t.contains(x.toLowerCase(Locale.ROOT))&&clickNodeOrParent(n)){log("ACTION","CLICK:"+x);return true;}for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)q.add(c);}}return false;}
 private boolean clickNodeOrParent(AccessibilityNodeInfo n){for(int i=0;n!=null&&i<5;i++,n=n.getParent())if(n.isClickable())return n.performAction(AccessibilityNodeInfo.ACTION_CLICK);return false;}
 private AccessibilityNodeInfo findById(AccessibilityNodeInfo r,String suffix){ArrayDeque<AccessibilityNodeInfo>q=new ArrayDeque<>();q.add(r);while(!q.isEmpty()){AccessibilityNodeInfo n=q.remove();String id=n.getViewIdResourceName();if(id!=null&&id.endsWith("/"+suffix))return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)q.add(c);}}return null;}
 private String snapshot(AccessibilityNodeInfo r){StringBuilder b=new StringBuilder();ArrayDeque<AccessibilityNodeInfo>q=new ArrayDeque<>();q.add(r);int count=0;while(!q.isEmpty()&&count++<800){AccessibilityNodeInfo n=q.remove();b.append(' ').append(nodeText(n));for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)q.add(c);}}return b.toString();}
 private String nodeText(AccessibilityNodeInfo n){return String.valueOf(n.getText())+" "+String.valueOf(n.getContentDescription())+" "+String.valueOf(n.getViewIdResourceName());}
 private boolean hasAny(String s,String...xs){for(String x:xs)if(s.contains(x))return true;return false;} private void log(String k,String v){android.util.Log.i("AntharesAgent",k+"="+v);}
}
