package us.anthares.agent;
public enum KwaiState { BOOT, KWAI_NOT_RUNNING, KWAI_STARTING, PERMISSION, ONBOARDING_INTEREST, START_GATE, MAIN, PROFILE, RESOURCE_LOADING, LOGIN_REQUIRED, AUTHENTICATING, AUTHENTICATED, READY, LAUNCHER_ANR, KWAI_CRASH, NETWORK_UNAVAILABLE, UNKNOWN_UI, AUTH_CHALLENGE, SESSION_EXPIRED }
